version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user/app/step1/bongmall
    overwrite: yes

permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user